language: java
notifications:
  email: false
jdk:
- openjdk8
stages:
- install
jobs:
  include:
  - stage: install
    script:
    - mvn clean install -B -V
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
