#%RAML 1.0 NamedExample

  id: 4eea64e6-5c87-462d-9fc5-c3fdd3a310fa
  name:
    - { languageCode: nb, languageText: EIER }
  description:
    - { languageCode: nb, languageText: Eier }
  administrativeStatus: OPEN
  version: 1.0.0
  versionValidFrom: 2010-01-01T15:00:00Z
  objectValidFrom: 2010-01-01T15:00:00Z
  objectCreatedDate: 2010-01-01T15:00:00Z
  objectCreatedBy: "OBV"
