#%RAML 1.0 Library
uses:
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml
  #InformationProvider: InformationProvider.raml
  MultilingualText: ./abstract/MultilingualText.raml
  #ExchangeChannel: ExchangeChannel.raml

types:
  ProvisionAgreement:
    description: #TODO:GSIM   The legal or other basis by which two parties agree to exchange data.
    type: IdentifiableArtefact.IdentifiableArtefact
    properties:
      informationProvider:
        type: string
        displayName: Leverandør
        description: #TODO: referanse til
      _link_property_informationProvider?:
        properties:
          InformationProvider?: nil

      regulation:
        type: string
        enum: #TODO: Hvilke kategorier har vi her???? Kanskje noen andre enn administrativeStatus
          - F #Frivillig undersøkelse
          - O #Oppgaveplikt undersøkelse (jfr. stl §2.2)
          - A #Administrativt register (jfr. stl §2.2 og §3.2)
        displayName: Hjemmelsgrunnlag
        description: #TODO: Legalor lawful basis to collect data
      status: #TODO:
        type: string
        enum: #TODO: Hvilke kategorier har vi her???? Kanskje noen andre enn administrativeStatus
        - DRAFT
        - INTERNAL
        - OPEN
        - DEPRECATED
        displayName: Status
        description: Leveranseavtalens status
      valuation?:
        type: string
        enum:  #TODO: Hvilke kategorier har vi her????
          - !str 1
          - !str 2
          - !str 3
          - !str 4
          - !str 5
        displayName: Verdivurdering
        description: Har noe med sensivitet og bruk å gjøre. kommer fra GDPR-teamet.
      changeManagement?:
        type: MultilingualText.MultilingualText
        displayName: Endringshåndtering
        description: Change management
      informationSource:
        type: MultilingualText.MultilingualText
        displayName: Kilde
        description: External source
      exchangeChannel:
        type: string
        displayName: Utvekslingskanal
        description: #TODO referanse, kanskje []?
      _link_property_exchangeChannel?:
        properties:
          ExchangeChannel?: nil

      frequency:
        type: string
        enum:  #TODO: Hvilke muligheter har vi her????
          - Løpende
          - Daglig
          - Ukentlig
          - Månedlig
          - Årlig
        displayName: Hyppighet
        description: The time frequency at which data is collected at regular intervals.

    example: !include ../examples/ProvisionAgreementExampleRef.json
