#%RAML 1.0 Library
uses:
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml

types:

  Role:
    description: The responsible function involved in the statistical Business Process.
    type: IdentifiableArtefact.IdentifiableArtefact

    example: !include ../examples/RoleExample1.json
